[7-0-stable] Lock json to 1.6.x to avoid ostruct removal
Newer versions of json gem remove ostruct causing us to either explicitly require ostruct where we need.

This is an alternative to depend on a stable version of json for older rubies.

```
Error:
ControllerHelperTest#test_respond_to:
NameError: uninitialized constant ControllerHelperTest::OpenStruct
    /rails/actionview/test/template/controller_helper_test.rb:25:in `test_respond_to'
```

https://buildkite.com/rails/rails/builds/108663#0190481d-cb6b-41b8-8c2a-db3d72a19964/1186-1194